apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: personal-website
          image: your-image:latest # Replace 'your-image' with the name of your container image after building
          ports:
            - containerPort: 8080