apiVersion: v1
kind: Service
metadata:
  name: personal-website-service
  namespace: personal-website
  labels: 
    app: personal-website
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: personal-website
